[build]
  command = "bun install tailwindcss postcss autoprefixer && bun run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200